# Generated by Django 3.1.6 on 2021-03-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_wiki"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wiki",
            name="parnet",
        ),
        migrations.AddField(
            model_name="wiki",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="web.wiki",
                verbose_name="父文章",
            ),
        ),
    ]
