# Generated by Django 3.1.6 on 2021-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_wiki_depth"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bucket",
            field=models.CharField(
                default="xxxxxx", max_length=128, verbose_name="COS桶"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.CharField(
                default="ap-chengdu", max_length=32, verbose_name="COS区域"
            ),
            preserve_default=False,
        ),
    ]
